version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/kryo.io.vn.conf
    depends_on:
      - frontend
    networks:
      - kryo-network

networks:
  kryo-network:
    driver: bridge