import { entertainment, steam, work, study } from '../../assets/img';

const products = [
    {
        id: 'acc netflix1',
        url: '/acc netflix1'.replaceAll(' ', '-'),
        name: 'Tài Khoản Netflix Premium 1 tháng - Xem phim chất lượng 4k và Full HD',
        category: ['App', 'Giải trí', 'Xem phim'],
        originPrice: 260000,
        discount: 62,
        img: entertainment[0],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'spotify-12m',
        url: '/spotify-12m'.replaceAll(' ', '-'),
        name: 'Gói gia hạn Spotify Premium 01 năm',
        category: ['App', 'Giải trí', 'Spotify', 'Nghe nhạc'],
        originPrice: 590000,
        discount: 49,
        img: entertainment[1],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'random',
        url: '/random'.replaceAll(' ', '-'),
        name: 'Random Code Steam',
        category: ['steam', 'random'],
        originPrice: 20000,
        discount: 55,
        img: steam[0],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'vncur 810660 vncur',
        url: '/vncur 810660 vncur'.replaceAll(' ', '-'),
        name: 'The Office Quest',
        category: ['Adventure', 'Indie'],
        originPrice: 109000,
        discount: 50,
        img: steam[1],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'vncur 810660 vncur',
        url: '/vncur 810660 vncur'.replaceAll(' ', '-'),
        name: 'The Office Quest',
        category: ['Adventure', 'Indie'],
        originPrice: 109000,
        discount: 50,
        img: steam[1],
        stockQuantity: 200,
        status: 'unavailable',
    },
    {
        id: 'acc busuu-premiumplus-1m',
        url: '/acc busuu-premiumplus-1m'.replaceAll(' ', '-'),
        name: 'Tài khoản học ngoại ngữ Busuu Premium Plus 1 Tháng',
        category: ['App', 'Học tập'],
        originPrice: 200000,
        discount: 92,
        img: study[0],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'khoa-hoc-coursera',
        url: '/khoa-hoc-coursera'.replaceAll(' ', '-'),
        name: 'Khóa học Coursera',
        category: ['App', 'Học tập'],
        originPrice: 150000,
        discount: 0,
        img: study[1],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'wins10pro',
        url: '/wins10pro'.replaceAll(' ', '-'),
        name: 'Windows 10 Professional CD Key',
        category: ['windows', 'Làm việc', 'microsoft'],
        originPrice: 400000,
        discount: 28,
        img: work[0],
        stockQuantity: 200,
        status: 'available',
    },
    {
        id: 'tk Doodly stan',
        url: '/tk Doodly stan'.replaceAll(' ', '-'),
        name: 'Tài khoản Doodly Standard vĩnh viễn',
        category: ['App', 'Làm việc'],
        originPrice: 4800000,
        discount: 88,
        img: work[1],
        stockQuantity: 200,
        status: 'available',
    },
];

export default products;
